# Generated by Django 5.1.4 on 2025-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_San_Mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='min_duration_months',
            field=models.IntegerField(default=1, help_text='Chỉ áp dụng cho lịch cố định'),
        ),
        migrations.AddField(
            model_name='court',
            name='schedule_type',
            field=models.CharField(choices=[('Fixed', 'Lịch cố định'), ('Single', 'Lịch ngày'), ('Flexible', 'Lịch linh hoạt')], default='Single', max_length=50),
        ),
        migrations.AddField(
            model_name='court',
            name='total_hours_per_month',
            field=models.IntegerField(blank=True, help_text='Chỉ áp dụng cho lịch linh hoạt', null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='type_court',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=255),
        ),
    ]
